export const CONNECT_EVENT = 'connect'
export const ERROR_EVENT = 'error'
export const CLOSE_EVENT = 'close'
export const ACCOUNTS_CHANGED = 'accountsChanged'
export const CHAIN_CHANGED = 'chainChanged'
export const DECRYPT_ERROR = 'DECRYPT_ERROR'
