export const RLOGIN_REFRESH_TOKEN = 'RLOGIN_REFRESH_TOKEN'
export const RLOGIN_ACCESS_TOKEN = 'RLOGIN_ACCESS_TOKEN'
export const DECRYPT_ERROR = 'DECRYPT_ERROR'

export const WALLETCONNECT = 'walletconnect'
